// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { ListVersionsv2Error, ListVersionsv2Response, GetVersionDetailsv2Error, GetVersionDetailsv2Response } from './types.gen';

export const client = createClient(createConfig());

export class DefaultService {
    constructor(public readonly httpRequest: BaseHttpRequest) { }
    
    /**
     * List API versions
     */
    public listVersionsv2<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<ListVersionsv2Response, ListVersionsv2Error, ThrowOnError>({
            ...options,
            url: '/'
        });
    }
    
    /**
     * Show API version details
     */
    public getVersionDetailsv2<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetVersionDetailsv2Response, GetVersionDetailsv2Error, ThrowOnError>({
            ...options,
            url: '/v2'
        });
    }
    
}