// This file is auto-generated by @hey-api/openapi-ts

export type ListVersionsv2Response = (unknown);

export type ListVersionsv2Error = (unknown);

export type GetVersionDetailsv2Response = (unknown);

export type GetVersionDetailsv2Error = unknown;